# This workflow will deploy your entire repo to your PHP hosting via SFTP on every push to main
# Uses SamKirkland/FTP-Deploy-Action for secure deployment

name: 🚀 SFTP Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts

      - name: SFTP upload files
        run: |
          find . -type f \
            ! -path './.git*' \
            ! -path './.github*' \
            ! -name 'README.md' \
            ! -name 'db.sql' \
            | while read file; do
                remotepath="${file#./}"
                dir=$(dirname "$remotepath")
                # Create remote directory using SFTP batch
                if [ "$dir" != "." ]; then
                  echo "mkdir \"${{ secrets.SFTP_TARGET_DIR }}/$dir\"" > sftp_batch.txt
                else
                  echo "" > sftp_batch.txt
                fi
                echo "put \"$file\" \"${{ secrets.SFTP_TARGET_DIR }}/$remotepath\"" >> sftp_batch.txt
                sftp -b sftp_batch.txt -i ~/.ssh/id_rsa -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}
                rm sftp_batch.txt
              done
