# This workflow will deploy your entire repo to your PHP hosting via SFTP on every push to main
# Uses SamKirkland/FTP-Deploy-Action for secure deployment

name: 🚀 SFTP Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP upload index.php only (debug)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_SERVER }} >> ~/.ssh/known_hosts
          # First create essential directories to ensure they exist
          echo "mkdir \"www/assets\"" > create_dirs.txt
          echo "mkdir \"www/assets/css\"" >> create_dirs.txt
          echo "mkdir \"www/assets/js\"" >> create_dirs.txt
          sftp -b create_dirs.txt -i ~/.ssh/id_rsa -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} || true
          rm create_dirs.txt

          # Then upload all files
          find . -type f \
            ! -path './.git*' \
            ! -path './.github*' \
            ! -name 'README.md' \
            ! -name 'db.sql' \
            | while read file; do
                remotepath="${file#./}"
                echo "put \"$file\" \"www/$remotepath\"" > sftp_batch.txt
                sftp -b sftp_batch.txt -i ~/.ssh/id_rsa -P ${{ secrets.SFTP_PORT }} ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} || true
                rm sftp_batch.txt
              done
