# This workflow will deploy your entire repo to your PHP hosting via SFTP on every push to main
# Uses SamKirkland/FTP-Deploy-Action for secure deployment

name: 🚀 SFTP Deploy to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy with SSH Key
        uses: atymic/sftp-deploy@v2.0.0
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: ./
          remote_path: ${{ secrets.SFTP_TARGET_DIR }}
          args: "-o StrictHostKeyChecking=no"
          dry_run: false
          delete_remote_files: false
          exclude: |
            .git*
            .github*
            README.md
            db.sql
